[pytest]
testpaths = src/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --alluredir allure-results
    --strict-markers
    --tb=short
    --verbose
markers =
    smoke: smoke tests
    regression: regression tests
    critical: critical functionality
    normal: normal functionality
    minor: minor functionality
    flaky: mark a test as flaky